package royaleserver.protocol;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Info {
	private Info() {}

	// Client messages
	public static final short CLIENT_HELLO = 10100;
	public static final short LOGIN = 10101;
	public static final short CLIENT_CAPABILITIES = 10107;
	public static final short KEEP_ALIVE = 10108;
	public static final short AUTHENTICATION_CHECK = 10112;
	public static final short SET_DEVICE_TOKEN = 10113;
	public static final short RESET_ACCOUNT = 10116;
	public static final short REPORT_USER = 10117;
	public static final short ACCOUNT_SWITCHED = 10118;
	public static final short UNLOCK_ACCOUNT = 10121;
	public static final short APPLE_BILLING_REQUEST = 10150;
	public static final short GOOGLE_BILLING_REQUEST = 10151;
	public static final short KUNLUN_BILLING_REQUEST = 10159;
	public static final short CHANGE_AVATAR_NAME = 10212;
	public static final short ASK_FOR_PLAYING_GAMECENTER_FRIENDS = 10512;
	public static final short ASK_FOR_PLAYING_FACEBOOK_FRIENDS = 10513;
	public static final short INBOX_OPENED = 10905;
	public static final short UNBIND_FACEBOOK_ACCOUNT = 12211;
	public static final short REQUEST_SECTOR_STATE = 12903;
	public static final short SECTOR_COMMAND = 12904;
	public static final short GET_CURRENT_BATTLE_REPLAY_DATA = 12905;
	public static final short SEND_BATTLE_EVENT = 12951;
	public static final short GO_HOME = 14101;
	public static final short END_CLIENT_TURN = 14102;
	public static final short START_MISSION = 14104;
	public static final short HOME_LOGIC_STOPPED = 14105;
	public static final short CANCEL_MATCHMAKE = 14107;
	public static final short CHANGE_HOME_NAME = 14108;
	public static final short VISIT_HOME = 14113;
	public static final short HOME_BATTLE_REPLAY = 14114;
	public static final short HOME_BATTLE_REPLAY_VIEWED = 14117;
	public static final short ACCEPT_CHALLENGE = 14120;
	public static final short CANCEL_CHALLENGE_MESSAGE = 14123;
	public static final short BIND_FACEBOOK_ACCOUNT = 14201;
	public static final short BIND_GAMECENTER_ACCOUNT = 14212;
	public static final short BIND_GOOGLE_SERVICE_ACCOUNT = 14262;
	public static final short CREATE_ALLIANCE = 14301;
	public static final short ASK_FOR_ALLIANCE_DATA = 14302;
	public static final short ASK_FOR_JOINABLE_ALLIANCES_LIST = 14303;
	public static final short ASK_FOR_ALLIANCE_STREAM = 14304;
	public static final short JOIN_ALLIANCE = 14305;
	public static final short CHANGE_ALLIANCE_MEMBER_ROLE = 14306;
	public static final short KICK_ALLIANCE_MEMBER = 14307;
	public static final short LEAVE_ALLIANCE = 14308;
	public static final short DONATE_ALLIANCE_UNIT = 14310;
	public static final short CHAT_TO_ALLIANCE_STREAM = 14315;
	public static final short CHANGE_ALLIANCE_SETTINGS = 14316;
	public static final short REQUEST_JOIN_ALLIANCE = 14317;
	public static final short SELECT_SPELLS_FROM_CO_OPEN = 14318;
	public static final short OFFER_CHEST_FOR_CO_OPEN = 14319;
	public static final short RESPOND_TO_ALLIANCE_JOIN_REQUEST = 14321;
	public static final short SEND_ALLIANCE_INVITATION = 14322;
	public static final short JOIN_ALLIANCE_USING_INVITATION = 14323;
	public static final short SEARCH_ALLIANCES = 14324;
	public static final short SEND_ALLIANCE_MAIL = 14330;
	public static final short ASK_FOR_ALLIANCE_RANKING_LIST = 14401;
	public static final short ASK_FOR_TV_CONTENT = 14402;
	public static final short ASK_FOR_AVATAR_RANKING_LIST = 14403;
	public static final short ASK_FOR_AVATAR_LOCAL_RANKING = 14404;
	public static final short ASK_FOR_AVATAR_STREAM = 14405;
	public static final short ASK_FOR_BATTLE_REPLAY_STREAM = 14406;
	public static final short ASK_FOR_LAST_AVATAR_TOURNAMENT_RESULTS = 14408;
	public static final short REMOVE_AVATAR_STREAM_ENTRY = 14418;
	public static final short AVATAR_NAME_CHECK_REQUEST = 14600;
	public static final short LOGIC_DEVICE_LINK_CODE_STATUS = 16000;
	public static final short ASK_FOR_JOINABLE_TOURNAMENTS = 16103;
	public static final short SEARCH_TOURNAMENTS = 16113;

	// Server messages
	public static final short SERVER_HELLO = 20100;
	public static final short LOGIN_FAILED = 20103;
	public static final short LOGIN_OK = 20104;
	public static final short FRIEND_LIST = 20105;
	public static final short KEEP_ALIVE_OK = 20108;
	public static final short CHAT_ACCOUNT_BAN_STATUS = 20118;
	public static final short BILLING_REQUEST_FAILED = 20121;
	public static final short UNLOCK_ACCOUNT_OK = 20132;
	public static final short UNLOCK_ACCOUNT_FAILED = 20133;
	public static final short APPLE_BILLING_PROCESSED_BY_SERVER = 20151;
	public static final short GOOGLE_BILLING_PROCESSED_BY_SERVER = 20152;
	public static final short KUNLUN_BILLING_PROCESSED_BY_SERVER = 20156;
	public static final short SHUTDOWN_STARTED = 20161;
	public static final short AVATAR_NAME_CHANGE_FAILED = 20205;
	public static final short AVATAR_IN_GAME_STATUS_UPDATED = 20206;
	public static final short ALLIANCE_ONLINE_STATUS_UPDATED = 20207;
	public static final short BATTLE_RESULT = 20225;
	public static final short AVATAR_NAME_CHECK_RESPONSE = 20300;
	public static final short OPPONENT_LEFT_MATCH_NOTIFICATION = 20801;
	public static final short OPPONENT_REJOINS_MATCH_NOTIFICATION = 20802;
	public static final short SECTOR_HEARBEAT = 21902;
	public static final short SECTOR_STATE = 21903;
	public static final short BATTLE_EVENT = 22952;
	public static final short PVP_MATCHMAKE_NOTIFICATION = 22957;
	public static final short OWN_HOME_DATA = 24101;
	public static final short OWN_AVATAR_DATA = 24102;
	public static final short OUT_OF_SYNC = 24104;
	public static final short STOP_HOME_LOGIC = 24106;
	public static final short MATCHMAKE_INFO = 24107;
	public static final short MATCHMAKE_FAILED = 24108;
	public static final short AVAILABLE_SERVER_COMMAND = 24111;
	public static final short UDP_CONNECTION_INFO = 24112;
	public static final short VISITED_HOME_DATA = 24113;
	public static final short HOME_BATTLE_REPLAY_DATA = 24114;
	public static final short SERVER_ERROR = 24115;
	public static final short HOME_BATTLE_REPLAY_FAILED = 24116;
	public static final short CHALLENGE_FAILED = 24121;
	public static final short CANCEL_CHALLENGE_DONE = 24124;
	public static final short CANCEL_MATCHMAKE_DONE = 24125;
	public static final short FACEBOOK_ACCOUNT_BOUND = 24201;
	public static final short FACEBOOK_ACCOUNT_ALREADY_BOUND = 24202;
	public static final short GAMECENTER_ACCOUNT_ALREADY_BOUND = 24212;
	public static final short FACEBOOK_ACCOUNT_UNBOUND = 24213;
	public static final short GOOGLE_SERVICE_ACCOUNT_BOUND = 24261;
	public static final short GOOGLE_SERVICE_ACCOUNT_ALREADY_BOUND = 24262;
	public static final short ALLIANCE_DATA = 24301;
	public static final short ALLIANCE_JOIN_FAILED = 24302;
	public static final short ALLIANCE_JOIN_OK = 24303;
	public static final short JOINABLE_ALLIANCE_LIST = 24304;
	public static final short ALLIANCE_LEAVE_OK = 24305;
	public static final short CHANGE_ALLIANCE_MEMBER_ROLE_OK = 24306;
	public static final short KICK_ALLIANCE_MEMBER_OK = 24307;
	public static final short ALLIANCE_MEMBER = 24308;
	public static final short ALLIANCE_MEMBER_REMOVED = 24309;
	public static final short ALLIANCE_LIST = 24310;
	public static final short ALLIANCE_STREAM = 24311;
	public static final short ALLIANCE_STREAM_ENTRY = 24312;
	public static final short ALLIANCE_STREAM_ENTRY_REMOVED = 24318;
	public static final short ALLIANCE_JOIN_REQUEST_OK = 24319;
	public static final short ALLIANCE_JOIN_REQUEST_FAILED = 24320;
	public static final short ALLIANCE_INVITATION_SEND_FAILED = 24321;
	public static final short ALLIANCE_INVITATION_SENT_OK = 24322;
	public static final short ALLIANCE_FULL_ENTRY_UPDATE = 24324;
	public static final short ALLIANCE_CREATE_FAILED = 24332;
	public static final short ALLIANCE_CHANGE_FAILED = 24333;
	public static final short ALLIANCE_RANKING_LIST = 24401;
	public static final short ALLIANCE_LOCAL_RANKING_LIST = 24402;
	public static final short AVATAR_RANKING_LIST = 24403;
	public static final short AVATAR_LOCAL_RANKING_LIST = 24404;
	public static final short ROYAL_TV_CONTENT = 24405;
	public static final short LAST_AVATAR_TOURNAMENT_RESULTS = 24407;
	public static final short AVATAR_STREAM = 24411;
	public static final short AVATAR_STREAM_ENTRY = 24412;
	public static final short BATTLE_REPORT_STREAM = 24413;
	public static final short AVATAR_STREAM_ENTRY_REMOVED = 24418;
	public static final short INBOX_LIST = 24445;
	public static final short INBOX_GLOBAL = 24446;
	public static final short INBOX_COUNT = 24447;
	public static final short DISCONNECTED = 25892;
	public static final short LOGIC_DEVICE_LINK_CODE_RESPONSE = 26002;
	public static final short LOGIC_DEVICE_LINK_NEW_DEVICE_LINKED = 26003;
	public static final short LOGIC_DEVICE_LINK_CODE_DEACTIVATED = 26004;
	public static final short LOGIC_DEVICE_LINK_RESPONSE = 26005;
	public static final short LOGIC_DEVICE_LINK_DONE = 26007;
	public static final short LOGIC_DEVICE_LINK_ERROR = 26008;

	public static final Map<Integer, String> messagesMap = createMessagesMap();

	private static Map<Integer, String> createMessagesMap() {
		Map<Integer, String> map = new HashMap<>();

		// Client messages
		map.put(10100, "ClientHello");
		map.put(10101, "Login");
		map.put(10107, "ClientCapabilities");
		map.put(10108, "KeepAlive");
		map.put(10112, "AuthenticationCheck");
		map.put(10113, "SetDeviceToken");
		map.put(10116, "ResetAccount");
		map.put(10117, "ReportUser");
		map.put(10118, "AccountSwitched");
		map.put(10121, "UnlockAccount");
		map.put(10150, "AppleBillingRequest");
		map.put(10151, "GoogleBillingRequest");
		map.put(10159, "KunlunBillingRequest");
		map.put(10212, "ChangeAvatarName");
		map.put(10512, "AskForPlayingGamecenterFriends");
		map.put(10513, "AskForPlayingFacebookFriends");
		map.put(10905, "InboxOpened");
		map.put(12211, "UnbindFacebookAccount");
		map.put(12903, "RequestSectorState");
		map.put(12904, "SectorCommand");
		map.put(12905, "GetCurrentBattleReplayData");
		map.put(12951, "SendBattleEvent");
		map.put(14101, "GoHome");
		map.put(14102, "EndClientTurn");
		map.put(14104, "StartMission");
		map.put(14105, "HomeLogicStopped");
		map.put(14107, "CancelMatchmake");
		map.put(14108, "ChangeHomeName");
		map.put(14113, "VisitHome");
		map.put(14114, "HomeBattleReplay");
		map.put(14117, "HomeBattleReplayViewed");
		map.put(14120, "AcceptChallenge");
		map.put(14123, "CancelChallengeMessage");
		map.put(14201, "BindFacebookAccount");
		map.put(14212, "BindGamecenterAccount");
		map.put(14262, "BindGoogleServiceAccount");
		map.put(14301, "CreateAlliance");
		map.put(14302, "AskForAllianceData");
		map.put(14303, "AskForJoinableAlliancesList");
		map.put(14304, "AskForAllianceStream");
		map.put(14305, "JoinAlliance");
		map.put(14306, "ChangeAllianceMemberRole");
		map.put(14307, "KickAllianceMember");
		map.put(14308, "LeaveAlliance");
		map.put(14310, "DonateAllianceUnit");
		map.put(14315, "ChatToAllianceStream");
		map.put(14316, "ChangeAllianceSettings");
		map.put(14317, "RequestJoinAlliance");
		map.put(14318, "SelectSpellsFromCoOpen");
		map.put(14319, "OfferChestForCoOpen");
		map.put(14321, "RespondToAllianceJoinRequest");
		map.put(14322, "SendAllianceInvitation");
		map.put(14323, "JoinAllianceUsingInvitation");
		map.put(14324, "SearchAlliances");
		map.put(14330, "SendAllianceMail");
		map.put(14401, "AskForAllianceRankingList");
		map.put(14402, "AskForTVContent");
		map.put(14403, "AskForAvatarRankingList");
		map.put(14404, "AskForAvatarLocalRanking");
		map.put(14405, "AskForAvatarStream");
		map.put(14406, "AskForBattleReplayStream");
		map.put(14408, "AskForLastAvatarTournamentResults");
		map.put(14418, "RemoveAvatarStreamEntry");
		map.put(14600, "AvatarNameCheckRequest");
		map.put(16000, "LogicDeviceLinkCodeStatus");
		map.put(16103, "AskForJoinableTournaments");
		map.put(16113, "SearchTournaments");

		// Server messages
		map.put(20100, "ServerHello");
		map.put(20103, "LoginFailed");
		map.put(20104, "LoginOk");
		map.put(20105, "FriendList");
		map.put(20108, "KeepAliveOk");
		map.put(20118, "ChatAccountBanStatus");
		map.put(20121, "BillingRequestFailed");
		map.put(20132, "UnlockAccountOk");
		map.put(20133, "UnlockAccountFailed");
		map.put(20151, "AppleBillingProcessedByServer");
		map.put(20152, "GoogleBillingProcessedByServer");
		map.put(20156, "KunlunBillingProcessedByServer");
		map.put(20161, "ShutdownStarted");
		map.put(20205, "AvatarNameChangeFailed");
		map.put(20206, "AvatarInGameStatusUpdated");
		map.put(20207, "AllianceOnlineStatusUpdated");
		map.put(20225, "BattleResult");
		map.put(20300, "AvatarNameCheckResponse");
		map.put(20801, "OpponentLeftMatchNotification");
		map.put(20802, "OpponentRejoinsMatchNotification");
		map.put(21902, "SectorHearbeat");
		map.put(21903, "SectorState");
		map.put(22952, "BattleEvent");
		map.put(22957, "PvpMatchmakeNotification");
		map.put(24101, "OwnHomeData");
		map.put(24102, "OwnAvatarData");
		map.put(24104, "OutOfSync");
		map.put(24106, "StopHomeLogic");
		map.put(24107, "MatchmakeInfo");
		map.put(24108, "MatchmakeFailed");
		map.put(24111, "AvailableServerCommand");
		map.put(24112, "UdpConnectionInfo");
		map.put(24113, "VisitedHomeData");
		map.put(24114, "HomeBattleReplayData");
		map.put(24115, "ServerError");
		map.put(24116, "HomeBattleReplayFailed");
		map.put(24121, "ChallengeFailed");
		map.put(24124, "CancelChallengeDone");
		map.put(24125, "CancelMatchmakeDone");
		map.put(24201, "FacebookAccountBound");
		map.put(24202, "FacebookAccountAlreadyBound");
		map.put(24212, "GamecenterAccountAlreadyBound");
		map.put(24213, "FacebookAccountUnbound");
		map.put(24261, "GoogleServiceAccountBound");
		map.put(24262, "GoogleServiceAccountAlreadyBound");
		map.put(24301, "AllianceData");
		map.put(24302, "AllianceJoinFailed");
		map.put(24303, "AllianceJoinOk");
		map.put(24304, "JoinableAllianceList");
		map.put(24305, "AllianceLeaveOk");
		map.put(24306, "ChangeAllianceMemberRoleOk");
		map.put(24307, "KickAllianceMemberOk");
		map.put(24308, "AllianceMember");
		map.put(24309, "AllianceMemberRemoved");
		map.put(24310, "AllianceList");
		map.put(24311, "AllianceStream");
		map.put(24312, "AllianceStreamEntry");
		map.put(24318, "AllianceStreamEntryRemoved");
		map.put(24319, "AllianceJoinRequestOk");
		map.put(24320, "AllianceJoinRequestFailed");
		map.put(24321, "AllianceInvitationSendFailed");
		map.put(24322, "AllianceInvitationSentOk");
		map.put(24324, "AllianceFullEntryUpdate");
		map.put(24332, "AllianceCreateFailed");
		map.put(24333, "AllianceChangeFailed");
		map.put(24401, "AllianceRankingList");
		map.put(24402, "AllianceLocalRankingList");
		map.put(24403, "AvatarRankingList");
		map.put(24404, "AvatarLocalRankingList");
		map.put(24405, "RoyalTVContent");
		map.put(24407, "LastAvatarTournamentResults");
		map.put(24411, "AvatarStream");
		map.put(24412, "AvatarStreamEntry");
		map.put(24413, "BattleReportStream");
		map.put(24418, "AvatarStreamEntryRemoved");
		map.put(24445, "InboxList");
		map.put(24446, "InboxGlobal");
		map.put(24447, "InboxCount");
		map.put(25892, "Disconnected");
		map.put(26002, "LogicDeviceLinkCodeResponse");
		map.put(26003, "LogicDeviceLinkNewDeviceLinked");
		map.put(26004, "LogicDeviceLinkCodeDeactivated");
		map.put(26005, "LogicDeviceLinkResponse");
		map.put(26007, "LogicDeviceLinkDone");
		map.put(26008, "LogicDeviceLinkError");

		return Collections.unmodifiableMap(map);
	}
}
